### ISSUE TITLE
Why cookies?

### ISSUE THREAD

**Issue by yusufff** [tcodina/todo-app#1]
Is there any special reason to use cookies instead of LocalStorage?

**Comment by tcodina** [comment]
Honestly, none at all. I agree that local storage would probably be more useful than cookies since it would work throughout all browsers & the data would be kept safe (As in, harder for it to be removed), but I didn't really think it through when making this project. Might look into it, but no promises ^^

**Comment by thomasvaeth** [comment]
I switched up cookies for localStorage. You can see everything I changed in #2.

**Comment by NotAmaan** [comment]
@tcodina Cookies are actually considered safer than localStorage (not sessionStorage though) and they are also more browser compatible since they have been around forever. But in this case, I think localStorage would be a better fit for storing user data.
Here's an [interesting post](https://www.rdegges.com/2018/please-stop-using-local-storage/) about cookies and localStorage.
